### ISSUE TITLE
strange segfault

### ISSUE THREAD

**Issue by 01micko** [woodenshoe-wi/rox-filer#4]
I could probably pinpoint the commit if needed. Also, I would have opened this on woof-ce/rox-filer but there is no issues tab. Here is the last line from `dmesg`

```
[10890.701565] ROX-Filer[5253]: segfault at 14 ip 0000000000448328 sp 00007ffd3e72bc00 error 4 in ROX-Filer[400000+98000]
```

At the time I was transferring a large file over wireless via smb. Didn't have many windows open. In the remote window (samba mount point), I tried to get the properties of the file when rox crashed.

HTH

**Comment by woodenshoe-wi** [comment]
Ok.  I have accepted your invitation, deleted and re-forked my rox-filer repo and transferred the issues in my fork back to their original locations.

I am reopening this issue because I am using the issues at my repo as a sort of todo list and I might be able to find some invalid memory usage problems with valgrind some time in the distant future...  I won’t be able to know for sure if it is this particular problem, but if ROX-Filer segfaulted there must be at least one thing wrong (probably more) to find...

**Comment by 01micko** [comment]
Thanks for accepting :+1: 

I guess I should compile with debug symbols and offer a decent backtrace in case it does happen again.
