### ISSUE TITLE
strange segfault

### ISSUE THREAD

**Issue by 01micko** [woodenshoe-wi/rox-filer#8]
I could probably pinpoint the commit if needed. Also, I would have opened this on woof-ce/rox-filer but there is no issues tab. Here is the last line from `dmesg`

```
[10890.701565] ROX-Filer[5253]: segfault at 14 ip 0000000000448328 sp 00007ffd3e72bc00 error 4 in ROX-Filer[400000+98000]
```

At the time I was transferring a large file over wireless via smb. Didn't have many windows open. In the remote window (samba mount point), I tried to get the properties of the file when rox crashed.

HTH

**Comment by 01micko** [comment]
BTW, the upload completed successfully after rox crashed so it is not a data loss bug. I have performed this type of operation many times before but I will note that my remote machines are much further from the wireless router than they were 6 months ago before I moved house. Maybe a timeout issue is involved?

**Comment by woodenshoe-wi** [comment]
Unfortunately, unless you can tell me how to reproduce the problem consistently, I’m not sure if I can do anything about it.

> Also, I would have opened this on woof-ce/rox-filer but there is no issues tab.

It’s not on by default for forked repos, but can be enabled in Settings.  I think you would be in a better position to fix the missing Issues tab than I am.  If others wanted to work on ROX-Filer I would rather the woof-ce/rox-filer repo be used so that I don’t have to merge pull requests when I have no time to test them.

I was planning to delete my fork of rox-filer and re-fork it from the woof-ce/rox-filer repo so that the pull requests get sent in the right direction by default, but was waiting until the first release from the woof-ce/rox-filer repo.  If you know that the woof-ce/rox-filer repo will actually be used going forward I can do this now already?  (The missing Issues tab was one of the reasons I was waiting.)

**Comment by 01micko** [comment]
It would nearly be impossible to reliably reproduce this issue so I'll close it. There are too many variables such as distance from the router, network traffic (wife was watching netflix on TV at the time) , atmospheric conditions, rf interference, you name it!

I have enabled issues at puppylinux-woof-ce/rox-filer so you can go from there.

cheers!

**Comment by 01micko** [comment]
I also added you as a collaborator if you decide to accept.
